# Header
menu:
  首頁: /
  關於: /about
  成員組: /groups
  專案: /projects
  公告與通知: /tags/公告與通知/
  在地化規範: /tags/在地化規範/
  新聞: /archives
  「加入我們」: https://pd.qq.com/g/undertalezhloc

# Content
excerpt_link: 閱讀全文

# MIIT ICP/IP/DOMAIN
beian: 
  enable: true
  number: 萌ICP備20255650號
  url: https://icp.gov.moe/?keyword=20255650

# Miscellaneous
favicon: /images/Logo.png
webclip: /images/webclip
brand:   /images/Banner_NoBg.png

# Jumbotron video & Hero image & Swiper
## Jumbotron video
video: 
  overlay: false
  path: /images/movie/
## Hero image
hero: 
  image: /images/Fullscreen.png
## Swiper
## https://github.com/nolimits4web/swiper
swiper: 
  enable: true

# Toc
## https://github.com/tscanlin/tocbot
toc: true

# Slogan
slogan: 
  primary: UNDERTALE 中文在地化社群
  secondary: UNDERTALE Chinese Localization Community
  pages: UNDERTALE 中文在地化社群
  posts: UNDERTALE 中文在地化社群
  archives: 專案釋出 / 公告與通知 / 在地化規範 / 部落格

# Library
libs:
  feather: /libs/feather/feather.min.js # V4.29.0
  lazysizes: /libs/lazysizes/lazysizes.min.js
  tocbot: /libs/tocbot/tocbot.min.js
  swiper: 
    css: /libs/swiper/swiper-bundle.min.css
    js:  /libs/swiper/swiper-bundle.min.js